# Generated by Django 4.1.3 on 2022-11-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='date_pub',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
