# Generated by Django 4.1.3 on 2022-11-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_ad_date_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='date_pub',
        ),
    ]
